version: "3.8"

services:
  frontend:
    build: ./frontend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/fr
    # Replace file system's local host with docker local host
    extra_hosts:
      - "docker.for.win.localhost:host-gateway"

  backend: 
    depends_on:
      - db
    build: ./backend
    expose:
      - "4000"
    ports: 
      - "4000:4000"
    links:
      - db
    volumes:
      - ./backend:/bk
    networks:
      - webappnetwork
    restart: always

  db:
    image: mongo:4.0-xenial
    container_name: mongodb
    ports:
      - 27017:27017
    command: --quiet
    networks:
      - webappnetwork

networks:
    webappnetwork:
        driver: bridge

volumes:
  db: